name: Run Tests

on:
  push:
    branches: [main]

  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v2

      - name: Setup python
        uses: actions/setup-python@v2
        with: 
          python-version: 3.12

      - name: Install dependencies
        run : |
          pip install -r requirements.txt

      - name: Run test
        run: pytest modules/tests